# Generated by Django 5.0.1 on 2024-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('salt', models.CharField(max_length=100, verbose_name='Salt')),
                ('expiry', models.DateField(max_length=100, verbose_name='Expiry')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
